name: Votifier
main: com.vexsoftware.votifier.nukkit.NuVotifier
version: @app.version@
description: A plugin that gets notified when votes are made for the server on toplists.
authors: [Ichbinjoe, blakeman8192, Kramer, tuxed, good777LUCKY]
api: ["1.0.11"]

permissions:
  nuvotifier.reload:
    description: Allows you to reload the NuVotifier plugin
    default: op
  nuvotifier.testvote:
    description: Allows you to send a test vote
    default: op
